[vpc_network]
description = "VPC Networks"
calls = ["global/networks"]
parse_function = "parse_networks"

[subnetwork]
description = "Subnetworks"
calls = ["aggregated/subnetworks"]
parse_function = "parse_subnets"

[firewall_rule]
description = "Firewall Rules"
calls = ["global/firewalls"]
parse_function = "parse_firewall_rules"

[instance_nics]
description = "Instance NICs"
calls = ["aggregated/instances"]
parse_function = "parse_instance_nics"

[instance_group]
description = "Instance Groups"
calls = ["aggregated/instanceGroups"]

[instance_group_manager]
description = "Instance Group Managers"
calls = ["aggregated/instanceGroupManagers"]

[instance_template]
description = "Instance Templates"
calls = ["aggregated/instanceTemplates"]

[forwarding_rule]
description = "Forwarding Rules"
calls = ["aggregated/forwardingRules", "global/forwardingRules"]
parse_function = "parse_forwarding_rules"

[healthcheck]
description = "Health Checks"
calls = ["aggregated/healthChecks"]

[cloud_router]
description = "Cloud Routers"
calls = ["aggregated/routers"]

[route]
description = "Routes"
calls = ["global/routes"]

[ssl_certificate]
description = "SSL Certificates"
calls = ["aggregated/sslCertificates"]

[security_policy]
description = "Cloud Armor Policy"
calls = ["aggregated/securityPolicies"]

[ssl_policy]
description = "SSL Policies"
calls = ["aggregated/sslPolicies"]

[vpn_tunnel]
description = "VPN Tunnels"
calls = ["aggregated/vpnTunnels"]

[cloud_vpn_gateway]
description = "Cloud VPN Gateways"
calls = ["aggregated/vpnGateways"]
parse_function = "parse_cloud_vpn_gateways"

[peer_vpn_gateway]
description = "Peer VPN Gateways"
calls = ["global/externalVpnGateways"]
parse_function = "parse_peer_vpn_gateways"
